### ISSUE TITLE
Javascript: Anonymous functions

### ISSUE THREAD

**Issue by Fuzzyma** [matmalkowski/full-stack-interview#67]
> The anonymous functions are those function created with the function constructor and hasn't any given name, those functions are commonly used as parameters to other functions.

Thats not quite right. Albeit anonymous functions technically **can** be created with the function constructor (`new Function(...)`) they almost never are. The examples show the "correct" way by using the function **keyword**.

Its worth noting, that double arrow functions can be used as anonymous functions, too.

**Comment by matmalkowski** [comment]
Resolved by #68
